# Makefile para Ejercicio 4
all: Ejercicio4_Cliente Ejercicio4_Servidor

Ejercicio4_Cliente: Ejercicio4_Cliente.cpp
	g++ -o Ejercicio4_Cliente Ejercicio4_Cliente.cpp

Ejercicio4_Servidor: Ejercicio4_Servidor.cpp
	g++ -o Ejercicio4_Servidor Ejercicio4_Servidor.cpp

clean:
	rm -f Ejercicio4_Cliente Ejercicio4_Servidor