
all: Ejercicio3_Lector Ejercicio3_Validador

Ejercicio3_Lector: Ejercicio3_Lector.cpp
	g++ -o Ejercicio3_Lector Ejercicio3_Lector.cpp

Ejercicio3_Validador: Ejercicio3_Validador.cpp
	g++ -o Ejercicio3_Validador Ejercicio3_Validador.cpp

clean:
	rm -f Ejercicio3_Lector Ejercicio3_Validador
