# Makefile para Ejercicio 5
all: Ejercicio5_Cliente Ejercicio5_Servidor

Ejercicio5_Cliente: Ejercicio5_Cliente.cpp
	g++ -o Ejercicio5_Cliente Ejercicio5_Cliente.cpp

Ejercicio5_Servidor: Ejercicio5_Servidor.cpp
	g++ -o Ejercicio5_Servidor Ejercicio5_Servidor.cpp

clean:
	rm -f Ejercicio5_Cliente Ejercicio5_Servidor